// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: example.sql

package queries

import (
	"context"
)

const createExample = `-- name: CreateExample :one
INSERT INTO examples (id, name)
VALUES ($1, $2)
RETURNING id, name, created_at, updated_at
`

type CreateExampleParams struct {
	ID   string
	Name string
}

func (q *Queries) CreateExample(ctx context.Context, arg CreateExampleParams) (Example, error) {
	row := q.db.QueryRowContext(ctx, createExample, arg.ID, arg.Name)
	var i Example
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExample = `-- name: GetExample :one
SELECT id, name, created_at, updated_at
FROM examples
WHERE id = $1
`

func (q *Queries) GetExample(ctx context.Context, id string) (Example, error) {
	row := q.db.QueryRowContext(ctx, getExample, id)
	var i Example
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExamples = `-- name: ListExamples :many
SELECT id, name, created_at, updated_at
FROM examples
ORDER BY created_at DESC, id DESC
LIMIT 100
`

func (q *Queries) ListExamples(ctx context.Context) ([]Example, error) {
	rows, err := q.db.QueryContext(ctx, listExamples)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Example{}
	for rows.Next() {
		var i Example
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
