// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"time"
)

type Example struct {
	ID        string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
