// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"context"
)

type Querier interface {
	CreateExample(ctx context.Context, arg CreateExampleParams) (Example, error)
	GetExample(ctx context.Context, id string) (Example, error)
	ListExamples(ctx context.Context) ([]Example, error)
}

var _ Querier = (*Queries)(nil)
